name = "adacovex"
description = "Ada/SPARK coverage, proof, and DO-178C compliance verification tool"
version = "0.1.0"

authors = ["bladeacer"]
maintainers = ["bladeacer <wg.nick.exe@gmail.com>"]
maintainers-logins = ["bladeacer"]
licenses = "Apache-2.0"
website = "https://github.com/bladeacer/adacovex"
tags = ["ada", "spark", "coverage", "do-178c", "compliance"]
