import { test, expect } from '@playwright/test';

test.describe('Dashboard layout', () => {
  // The dashboard is a single inlined ~220 KB document; cold browser starts
  // (first load of the session) can exceed the 30 s default, so give each
  // test a generous budget.
  test.setTimeout(60000);
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('renders header with title, theme selector, and search', async ({ page }) => {
    await expect(page.locator('h1')).toContainText('adacovex Dashboard');
    await expect(page.locator('#theme-select')).toBeVisible();
    await expect(page.locator('#global-search')).toBeVisible();
  });

  test('all seven tabs are present', async ({ page }) => {
    const tabs = ['overview', 'proof', 'tests', 'compliance', 'deps', 'charts', 'credits'];
    for (const tab of tabs) {
      await expect(page.locator(`[data-tab="${tab}"]`)).toBeVisible();
    }
  });

  test('overview tab shows badges and metrics', async ({ page }) => {
    await page.click('[data-tab="overview"]');
    await expect(page.locator('.badge-container')).toBeVisible();
    // Five cards: Robustness, SPARK Proof, Tests, Doc Coverage, Dependency Scope.
    await expect(page.locator('#tab-overview .chart-card')).toHaveCount(5, { timeout: 5000 });
  });

  test('overview tests chart has a readout line below the donut', async ({ page }) => {
    await page.click('[data-tab="overview"]');
    // The Tests chart card always carries a readout with the pass/fail counts.
    const testsCard = page.locator('#tab-overview .chart-card', { hasText: 'Tests' });
    await expect(testsCard.locator('.chart-readout')).toBeVisible();
  });

  test('proof tab shows SPARK level and VCs', async ({ page }) => {
    await page.click('[data-tab="proof"]');
    await expect(page.locator('#tab-proof .spark')).toBeVisible();
    await expect(page.locator('#tab-proof', { hasText: 'Total VCs' })).toBeVisible();
  });

  test('tests tab shows pass rate gauge and category table', async ({ page }) => {
    await page.click('[data-tab="tests"]');
    await expect(page.locator('text=Test Pass Rate')).toBeVisible();
    await expect(page.locator('#tab-tests .compliance-gauge-wrap')).toBeVisible();
    await expect(page.locator('#tab-tests table', { hasText: 'Category' })).toBeVisible();
  });

  test('compliance tab shows target level', async ({ page }) => {
    await page.click('[data-tab="compliance"]');
    await expect(page.locator('#tab-compliance .gauge-target').first()).toBeVisible();
    await expect(page.locator('#tab-compliance .gauge-achieved').first()).toBeVisible();
  });

  test('dependencies tab shows scope badges', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    // The resolved graph has dev, transitive and vendored components; the
    // scope legend always lists all four scopes (base may be empty).
    await expect(page.locator('.dep-badge.scope-dev').first()).toBeVisible();
    await expect(page.locator('.dep-badge.scope-transitive').first()).toBeVisible();
    await expect(page.locator('.dep-badge.scope-vendored').first()).toBeVisible();
    await expect(page.locator('.scope-legend-prominent', { hasText: 'base' })).toBeVisible();
  });

  test('charts tab renders hand-rolled charts', async ({ page }) => {
    await page.click('[data-tab="charts"]');
    // Four chart cards use hand-rolled markup: SPARK Proof donut and Tests
    // Pass/Fail donut (.donut), Proof Check Types and Test Results bars
    // (.hbar rows).
    const donuts = page.locator('#tab-charts .donut');
    await expect(donuts).toHaveCount(2, { timeout: 5000 });
    const bars = page.locator('#tab-charts .hbar');
    await expect(bars.count()).resolves.toBeGreaterThanOrEqual(6);
  });

  test('credits tab shows third-party libraries', async ({ page }) => {
    await page.click('[data-tab="credits"]');
    await expect(page.locator('#tab-credits').getByRole('link', { name: 'nomnoml' })).toBeVisible();
    await expect(page.locator('#tab-credits').getByRole('link', { name: 'FlexSearch' })).toBeVisible();
    await expect(page.locator('#tab-credits').getByRole('link', { name: 'Charts.css' })).toBeVisible();
    await expect(page.locator('#credits-playwright')).toContainText('test / Apache-2.0');
  });

  test('footer shows generated by adacovex', async ({ page }) => {
    await expect(page.locator('.footer')).toContainText('Generated by adacovex');
  });

  test('search box filters deps', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    const search = page.locator('#global-search');
    await search.fill('gnat');
    await expect(page.locator('.search-hits.active')).toBeVisible();
  });

  test('search finds page content like orphan tags', async ({ page }) => {
    await page.click('[data-tab="compliance"]');
    const search = page.locator('#global-search');
    // The full-text index is case-folded, so a lowercase query matches page
    // text such as "Orphan Tags" and jumps to the compliance tab.
    await search.fill('orphan');
    const hits = page.locator('.search-hits.active .search-hit');
    await expect(hits.first()).toBeVisible();
  });

  test('selecting a dependency opens the split-view detail panel', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    const firstDep = page.locator('.dep-link').first();
    await expect(firstDep).toBeVisible();
    await firstDep.click();
    // The split layout activates on the .dep-split container, docking the
    // tree/diagram left and the detail card right; the popup is shown.
    await expect(page.locator('#dep-split')).toHaveClass(/dep-split-active/);
    await expect(page.locator('#dep-detail-popup')).toBeVisible();
    // Closing returns the view to full width.
    await page.locator('.dep-details-close').click();
    await expect(page.locator('#dep-detail-popup')).toBeHidden();
    await expect(page.locator('#dep-split')).not.toHaveClass(/dep-split-active/);
  });

  test('diagram view also opens the split-view detail panel', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    await page.click('.dep-view-switch button[data-view="nomnoml"]');
    await expect(page.locator('#dep-nomnoml-view')).toBeVisible();
    // The tree is hidden in diagram mode. The shared detail bridge is used
    // by the SVG node boxes and opens the same panel for either view.
    await page.evaluate(() => (window as any).showDepDetails(1));
    await expect(page.locator('#dep-split')).toHaveClass(/dep-split-active/);
    await expect(page.locator('#dep-detail-popup')).toBeVisible();
  });

  test('diagram SVG nodes are clickable with real hitboxes', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    await page.click('.dep-view-switch button[data-view="nomnoml"]');
    // The diagram is rendered as SVG; every node's box carries data-name and
    // opens the detail panel when clicked (no manual canvas hit-testing).
    const node = page.locator('#nomnoml-canvas [data-name]').first();
    await expect(node).toBeVisible({ timeout: 5000 });
    await node.click();
    await expect(page.locator('#dep-detail-popup')).toBeVisible();
    await expect(page.locator('#dep-split')).toHaveClass(/dep-split-active/);
  });

  test('test scope filter checkbox is present', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    // The checkbox input itself is visually hidden (opacity 0), so target
    // its visible label, like the other scope filters.
    await expect(page.locator('label:has(#filter-test)')).toBeVisible();
    // The scope legend lists every scope including test.
    await expect(page.locator('.scope-legend-prominent', { hasText: 'test' })).toBeVisible();
  });

  test('system dependencies are marked and shown without a licence', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    // The scanned project references system tools (python3, git, ...); at
    // least one resolves to a pkg:generic/* system dependency with a badge.
    const systemBadges = page.locator('.dep-badge.scope-system');
    if (await systemBadges.count() > 0) {
      await expect(systemBadges.first()).toBeVisible();
      await systemBadges.first().scrollIntoViewIfNeeded();
      await page.locator('.dep-node[data-scope="system"] .dep-link').first().click({ force: true });
      await expect(page.locator('.dep-system-note')).toBeVisible();
    }
  });


  test('dep name filter narrows the tree', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    const filter = page.locator('#dep-filter');
    await filter.fill('gnat');
    const visible = await page.locator('.dep-node:visible').count();
    const total = await page.locator('.dep-node').count();
    expect(visible).toBeGreaterThan(0);
    expect(visible).toBeLessThan(total);
    // Clearing restores the full tree.
    await filter.fill('');
    await expect(page.locator('.dep-node')).toHaveCount(total);
  });

  test('scope checkbox hides its scope', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    const devNodes = page.locator('.dep-node[data-scope="dev"]');
    const before = await devNodes.count();
    expect(before).toBeGreaterThan(0);
    await page.click('label:has(#filter-dev)');
    await expect(devNodes.first()).toBeHidden();
  });

  test('theme switching works', async ({ page }) => {
    const select = page.locator('#theme-select');
    await select.selectOption('dark');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    await select.selectOption('light');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  });

  test('responsive layout on mobile', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await expect(page.locator('h1')).toBeVisible();
    await expect(page.locator('.tabs')).toBeVisible();
  });

  test('search scrolls to a page section and flashes it', async ({ page }) => {
    const search = page.locator('#global-search');
    await search.fill('orphan');
    const hit = page.locator('.search-hits.active .search-hit').first();
    await expect(hit).toBeVisible();
    await hit.click();
    // Selecting a content hit switches to the compliance tab AND marks the
    // matched row with the temporary .search-flash marker (scroll target).
    await expect(page.locator('[data-tab="compliance"]')).toHaveClass(/active/);
    const flashed = page.locator('#tab-compliance .search-flash');
    await expect(flashed.first()).toBeVisible();
  });

  test('overview paired cards share the row 50-50', async ({ page }) => {
    await page.click('[data-tab="overview"]');
    const doc = page.locator('#tab-overview .chart-pair .chart-card', { hasText: 'Doc Coverage' });
    const scope = page.locator('#tab-overview .chart-pair .chart-card', { hasText: 'Dependency Scope' });
    await expect(doc).toBeVisible();
    await expect(scope).toBeVisible();
    const db = await doc.boundingBox();
    const sb = await scope.boundingBox();
    expect(db).not.toBeNull();
    expect(sb).not.toBeNull();
    // Each card takes about half the row (allow ~5% for gap/rounding).
    const ratio = db!.width / sb!.width;
    expect(ratio).toBeGreaterThan(0.95);
    expect(ratio).toBeLessThan(1.05);
  });

  test('proof check bars scale with their value', async ({ page }) => {
    await page.click('[data-tab="charts"]');
    const card = page.locator('#tab-charts .chart-card', { hasText: 'Proof Check Types' });
    const tracks = card.locator('.hbar-track');
    const n = await tracks.count();
    expect(n).toBeGreaterThanOrEqual(4);
    // The track itself never carries a width (flex-fills full width); only
    // the green/red fills scale against the largest category.
    const styledTracks = await tracks.evaluateAll((els) =>
      els.filter((t) => t.getAttribute('style')).length
    );
    expect(styledTracks).toBe(0);
    const widths = await tracks.evaluateAll((els) =>
      els.map((t) => {
        const i = t.querySelector('i');
        return i ? parseInt((i.style.width || '0').replace('%', ''), 10) : -1;
      })
    );
    expect(widths.some((w) => w === 100)).toBe(true);        // largest category fills
    expect(widths.some((w) => w >= 0 && w < 100)).toBe(true); // smaller categories scale
  });

  test('all dashboard links share the accent colour', async ({ page }) => {
    const colours = await page.locator('a').evaluateAll((links) =>
      Array.from(new Set(links.map((a) => getComputedStyle(a).color)))
    );
    // A single distinct computed colour means no link falls back to the
    // browser's default blue/purple.
    expect(colours.length).toBe(1);
  });
});
