import { test, expect } from '@playwright/test';

test.describe('Dashboard layout', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('renders header with title, theme selector, and search', async ({ page }) => {
    await expect(page.locator('h1')).toContainText('adacovex Dashboard');
    await expect(page.locator('#theme-select')).toBeVisible();
    await expect(page.locator('#global-search')).toBeVisible();
  });

  test('all seven tabs are present', async ({ page }) => {
    const tabs = ['overview', 'proof', 'tests', 'compliance', 'deps', 'charts', 'credits'];
    for (const tab of tabs) {
      await expect(page.locator(`[data-tab="${tab}"]`)).toBeVisible();
    }
  });

  test('overview tab shows badges and metrics', async ({ page }) => {
    await page.click('[data-tab="overview"]');
    await expect(page.locator('.badge-container')).toBeVisible();
    // Five cards: Robustness, SPARK Proof, Tests, Test Categories, Doc Coverage.
    await expect(page.locator('#tab-overview .chart-card')).toHaveCount(5, { timeout: 5000 });
  });

  test('proof tab shows SPARK level and VCs', async ({ page }) => {
    await page.click('[data-tab="proof"]');
    await expect(page.locator('#tab-proof .spark')).toBeVisible();
    await expect(page.locator('#tab-proof', { hasText: 'Total VCs' })).toBeVisible();
  });

  test('tests tab shows pass rate gauge and category table', async ({ page }) => {
    await page.click('[data-tab="tests"]');
    await expect(page.locator('text=Test Pass Rate')).toBeVisible();
    await expect(page.locator('#tab-tests .compliance-gauge-wrap')).toBeVisible();
    await expect(page.locator('#tab-tests table', { hasText: 'Category' })).toBeVisible();
  });

  test('compliance tab shows target level', async ({ page }) => {
    await page.click('[data-tab="compliance"]');
    await expect(page.locator('text=Target:')).toBeVisible();
    await expect(page.locator('text=Achieved:')).toBeVisible();
  });

  test('dependencies tab shows scope badges', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    // The resolved graph has dev, transitive and vendored components; the
    // scope legend always lists all four scopes (base may be empty).
    await expect(page.locator('.dep-badge.scope-dev').first()).toBeVisible();
    await expect(page.locator('.dep-badge.scope-transitive').first()).toBeVisible();
    await expect(page.locator('.dep-badge.scope-vendored').first()).toBeVisible();
    await expect(page.locator('.scope-legend-prominent', { hasText: 'base' })).toBeVisible();
  });

  test('charts tab renders charts.css charts', async ({ page }) => {
    await page.click('[data-tab="charts"]');
    // Four charts-css cards: SPARK Proof donut, Proof Check Types column,
    // Test Results bar, Tests Pass/Fail pie.
    const charts = page.locator('#tab-charts .charts-css');
    await expect(charts).toHaveCount(4, { timeout: 5000 });
  });

  test('credits tab shows third-party libraries', async ({ page }) => {
    await page.click('[data-tab="credits"]');
    await expect(page.locator('#tab-credits').getByRole('link', { name: 'Charts.css' })).toBeVisible();
    await expect(page.locator('#tab-credits').getByRole('link', { name: 'nomnoml' })).toBeVisible();
  });

  test('footer shows generated by adacovex', async ({ page }) => {
    await expect(page.locator('.footer')).toContainText('Generated by adacovex');
  });

  test('search box filters deps', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    const search = page.locator('#global-search');
    await search.fill('gnat');
    await expect(page.locator('.search-hits.active')).toBeVisible();
  });

  test('selecting a dependency opens the split-view detail panel', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    const firstDep = page.locator('.dep-link').first();
    await expect(firstDep).toBeVisible();
    await firstDep.click();
    // The split layout activates on the .dep-split container, docking the
    // tree/diagram left and the detail card right; the popup is shown.
    await expect(page.locator('#dep-split')).toHaveClass(/dep-split-active/);
    await expect(page.locator('#dep-detail-popup')).toBeVisible();
    // Closing returns the view to full width.
    await page.locator('.dep-details-close').click();
    await expect(page.locator('#dep-detail-popup')).toBeHidden();
    await expect(page.locator('#dep-split')).not.toHaveClass(/dep-split-active/);
  });

  test('diagram view also opens the split-view detail panel', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    await page.click('.dep-view-switch button[data-view="nomnoml"]');
    await expect(page.locator('#dep-nomnoml-view')).toBeVisible();
    const firstDep = page.locator('.dep-link').first();
    await firstDep.click();
    await expect(page.locator('#dep-split')).toHaveClass(/dep-split-active/);
    await expect(page.locator('#dep-detail-popup')).toBeVisible();
  });

  test('system dependencies are marked and shown without a licence', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    // The scanned project references system tools (python3, git, ...); at
    // least one resolves to a pkg:generic/* system dependency with a badge.
    const systemBadges = page.locator('.dep-badge.scope-system');
    if (await systemBadges.count() > 0) {
      await expect(systemBadges.first()).toBeVisible();
      await systemBadges.first().scrollIntoViewIfNeeded();
      await page.locator('.dep-link').first().click();
      await expect(page.locator('.dep-system-note')).toBeVisible();
    }
  });


  test('dep name filter narrows the tree', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    const filter = page.locator('#dep-filter');
    await filter.fill('gnat');
    const visible = await page.locator('.dep-node:visible').count();
    const total = await page.locator('.dep-node').count();
    expect(visible).toBeGreaterThan(0);
    expect(visible).toBeLessThan(total);
    // Clearing restores the full tree.
    await filter.fill('');
    await expect(page.locator('.dep-node')).toHaveCount(total);
  });

  test('scope checkbox hides its scope', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    const devNodes = page.locator('.dep-node[data-scope="dev"]');
    const before = await devNodes.count();
    expect(before).toBeGreaterThan(0);
    await page.click('label:has(#filter-dev)');
    await expect(devNodes.first()).toBeHidden();
  });

  test('theme switching works', async ({ page }) => {
    const select = page.locator('#theme-select');
    await select.selectOption('dark');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    await select.selectOption('light');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  });

  test('responsive layout on mobile', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await expect(page.locator('h1')).toBeVisible();
    await expect(page.locator('.tabs')).toBeVisible();
  });
});
