import { test, expect } from '@playwright/test';

test.describe('Dashboard layout', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('renders header with title, theme selector, and search', async ({ page }) => {
    await expect(page.locator('h1')).toContainText('adacovex Dashboard');
    await expect(page.locator('#theme-select')).toBeVisible();
    await expect(page.locator('#global-search')).toBeVisible();
  });

  test('all seven tabs are present', async ({ page }) => {
    const tabs = ['overview', 'proof', 'tests', 'compliance', 'deps', 'charts', 'credits'];
    for (const tab of tabs) {
      await expect(page.locator(`[data-tab="${tab}"]`)).toBeVisible();
    }
  });

  test('overview tab shows badges and metrics', async ({ page }) => {
    await page.click('[data-tab="overview"]');
    await expect(page.locator('.badge-container')).toBeVisible();
    await expect(page.locator('.chart-card')).toHaveCount(3, { timeout: 5000 });
  });

  test('proof tab shows SPARK level and VCs', async ({ page }) => {
    await page.click('[data-tab="proof"]');
    await expect(page.locator('.spark')).toBeVisible();
    await expect(page.locator('text=VCs Proved')).toBeVisible();
  });

  test('tests tab shows pass/fail donut', async ({ page }) => {
    await page.click('[data-tab="tests"]');
    await expect(page.locator('text=Pass / Fail')).toBeVisible();
    await expect(page.locator('.charts-css.pie')).toBeVisible();
  });

  test('compliance tab shows target level', async ({ page }) => {
    await page.click('[data-tab="compliance"]');
    await expect(page.locator('text=Target:')).toBeVisible();
    await expect(page.locator('text=Achieved:')).toBeVisible();
  });

  test('dependencies tab shows scope badges', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    await expect(page.locator('.scope-base')).toBeVisible();
    await expect(page.locator('.scope-dev')).toBeVisible();
    await expect(page.locator('.scope-transitive')).toBeVisible();
    await expect(page.locator('.scope-vendored')).toBeVisible();
  });

  test('charts tab renders charts.css charts', async ({ page }) => {
    await page.click('[data-tab="charts"]');
    const charts = page.locator('.charts-css');
    await expect(charts).toHaveCount(5, { timeout: 5000 });
  });

  test('credits tab shows third-party libraries', async ({ page }) => {
    await page.click('[data-tab="credits"]');
    await expect(page.locator('text=Charts.css')).toBeVisible();
    await expect(page.locator('text=nomnoml')).toBeVisible();
  });

  test('footer shows generated by adacovex', async ({ page }) => {
    await expect(page.locator('.footer')).toContainText('Generated by adacovex');
  });

  test('search box filters deps', async ({ page }) => {
    await page.click('[data-tab="deps"]');
    const search = page.locator('#global-search');
    await search.fill('gnat');
    await expect(page.locator('.search-hits.active')).toBeVisible();
  });

  test('theme switching works', async ({ page }) => {
    const select = page.locator('#theme-select');
    await select.selectOption('dark');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    await select.selectOption('light');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  });

  test('responsive layout on mobile', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await expect(page.locator('h1')).toBeVisible();
    await expect(page.locator('.tabs')).toBeVisible();
  });
});
