with Ada.Strings.Unbounded;

package body Adacovex.Completion is

   use Ada.Strings.Unbounded;

   --  Case-insensitive equality for the shell name.
   function Same_Shell (S : String; Name : String) return Boolean is
      Lower : String (1 .. 4) := (others => ' ');
      Len   : Natural := 0;
   begin
      for I in S'Range loop
         if Len < 4 then
            Len := Len + 1;
            if S (I) in 'A' .. 'Z' then
               Lower (Len) := Character'Val (Character'Pos (S (I)) + 32);
            else
               Lower (Len) := S (I);
            end if;
         end if;
      end loop;
      return Len = Name'Length and then Lower (1 .. Len) = Name;
   end Same_Shell;

   --  Emit a \\n-terminated line into the buffer.
   procedure Emit (R : in out Unbounded_String; Line : String) is
   begin
      Append (R, Line);
      Append (R, ASCII.LF);
   end Emit;

   function Gen_Bash (Flags : String) return String is
      R : Unbounded_String;
   begin
      Emit (R, "# bash completion for adacovex -- generated by `adacovex completion bash`");
      Emit (R, "# source this file from ~/.bashrc, or install it as:");
      Emit (R, "#   adacovex completion bash > ~/.local/share/bash-completion/completions/adacovex");
      Emit (R, "");
      Emit (R, "_adacovex_complete() {");
      Emit (R, "    local cur=""${COMP_WORDS[COMP_CWORD]}""");
      Emit (R, "    local prev=""${COMP_WORDS[COMP_CWORD-1]}""");
      Emit (R, "    local flags=""" & Flags & """");
      Emit (R, "    local subs=""sbom prove status completion man help""");
      Emit (R, "    case ""$prev"" in");
      Emit (R, "        completion) COMPREPLY=( $(compgen -W ""bash fish zsh pwsh"" -- ""$cur"") ); return ;;");
      Emit (R, "    esac");
      Emit (R, "    if [[ $cur == -* ]]; then");
      Emit (R, "        COMPREPLY=( $(compgen -W ""$flags"" -- ""$cur"") )");
      Emit (R, "        return");
      Emit (R, "    fi");
      Emit (R, "    COMPREPLY=( $(compgen -W ""$subs"" -- ""$cur"") )");
      Emit (R, "}");
      Emit (R, "complete -F _adacovex_complete adacovex covex");
      Emit (R, "");
      return To_String (R);
   end Gen_Bash;

   function Gen_Fish (Flags : String) return String is
      R   : Unbounded_String;
      F   : String := Flags;
      Pos : Natural := F'First;
   begin
      Emit (R, "# fish completion for adacovex - generated by `adacovex completion fish`");
      Emit (R, "# install as ~/.config/fish/completions/adacovex.fish (and covex.fish)");
      Emit (R, "complete -c adacovex -f");
      Emit (R, "complete -c covex -f");
      while Pos <= F'Last loop
         declare
            Fin : Natural := Pos;
         begin
            while Fin <= F'Last and then F (Fin) /= ' ' loop
               Fin := Fin + 1;
            end loop;
            Emit (R, "complete -c adacovex -l " & F (Pos .. Fin - 1));
            Emit (R, "complete -c covex -l " & F (Pos .. Fin - 1));
            Pos := Fin + 1;
         end;
      end loop;
      Emit (R, "complete -c adacovex -n '__fish_use_subcommand' -a 'status sbom prove man completion'");
      Emit (R, "complete -c covex -n '__fish_use_subcommand' -a 'status sbom prove man completion'");
      Emit (R, "");
      return To_String (R);
   end Gen_Fish;

   function Gen_Zsh (Flags : String) return String is
      R : Unbounded_String;
   begin
      Emit (R, "#compdef adacovex covex");
      Emit (R, "# zsh completion for adacovex - generated by `adacovex completion zsh`");
      Emit (R, "# install as fpath entry or: adacovex completion zsh > ${fpath[1]}/_adacovex");
      Emit (R, "_adacovex() {");
      Emit (R, "  local -a flags subs");
      Emit (R, "  flags=(" & Flags & ")");
      Emit (R, "  subs=(sbom prove status man completion help)");
      Emit (R, "  if [[ $words[CURRENT] == -* ]]; then");
      Emit (R, "    compadd -- ${flags[*]}");
      Emit (R, "  elif [[ $words[CURRENT-1] == completion ]]; then");
      Emit (R, "    compadd -- bash fish zsh pwsh");
      Emit (R, "  else");
      Emit (R, "    compadd -- ${subs[*]}");
      Emit (R, "  fi");
      Emit (R, "}");
      Emit (R, "compdef _adacovex adacovex covex");
      Emit (R, "");
      return To_String (R);
   end Gen_Zsh;

   function Gen_Pwsh (Flags : String) return String is
      R : Unbounded_String;
   begin
      Emit (R, "# PowerShell completion for adacovex - generated by `adacovex completion pwsh`");
      Emit (R, "# add to $PROFILE or install with:");
      Emit (R, "#   adacovex completion pwsh > $env:USERPROFILE\\Documents\\PowerShell\\adacovex-completion.ps1");
      Emit (R, "Register-ArgumentCompleter -Native -CommandName adacovex,covex -ScriptBlock {");
      Emit (R, "    param(\$wordToComplete, \$commandAst, \$cursorPosition)");
      Emit (R, "    \$flags = @(");
      declare
         F    : String := Flags;
         Pos  : Natural := F'First;
         Ct   : Natural := 0;
      begin
         while Pos <= F'Last loop
            declare
               Fin : Natural := Pos;
            begin
               while Fin <= F'Last and then F (Fin) /= ' ' loop
                  Fin := Fin + 1;
               end loop;
               if Ct > 0 then
                  Append (R, ASCII.LF & "              ");
               end if;
               Append (R, "'--" & F (Pos .. Fin - 1) & "'");
               Pos := Fin + 1;
               Ct := Ct + 1;
            end;
         end loop;
      end;
      Emit (R, ")");
      Emit (R, "    \$flags | Where-Object { \$_ -like ""\$wordToComplete*"" } | ForEach-Object {");
      Emit (R, "        [System.Management.Automation.CompletionResult]::new(\$_, \$_, 'ParameterName', \$_)");
      Emit (R, "    }");
      Emit (R, "}");
      Emit (R, "");
      return To_String (R);
   end Gen_Pwsh;

   function Generate (Shell : String; Flags : String) return String is
   begin
      if Same_Shell (Shell, "fish") then
         return Gen_Fish (Flags);
      elsif Same_Shell (Shell, "zsh") then
         return Gen_Zsh (Flags);
      elsif Same_Shell (Shell, "pwsh") then
         return Gen_Pwsh (Flags);
      else
         return Gen_Bash (Flags);
      end if;
   end Generate;

end Adacovex.Completion;