#!/usr/bin/env python3
"""Generate src/adacovex-dashboard_template.ads from resources/dashboard.html.

The --serve dashboard used to be written out line by line from Ada string
literals, mixing HTML/CSS/JS with rendering logic.  The static page shell
(doctype, CSS, header with the theme dropdown + Save settings button, footer
with the embed hint, and the theme script) now lives in
resources/dashboard.html, and this script bundles it into the binary at
build time as a single String constant.

Two placeholders are substituted at run time by
Adacovex.Renderers.HTML.Render_Dashboard:

  __CARDS__   replaced with the dynamic card markup (badges, source
              overview, SPARK proof, tests, compliance, HLR traceability).
  __THEME__   replaced with the initial dashboard theme
              (system / light / dark), used by the theme script via the
              <html data-initial-theme> attribute.

The generated file is committed so the tree builds without running this
script, and `make build` regenerates it (byte-identical when nothing
changed) so the served page never drifts from the template.

Ada string literals cannot span lines, so each template line is emitted as
its own quoted segment joined with ` & ASCII.LF & `.  Embedded double quotes
are doubled per Ada syntax.  The template must stay pure ASCII (enforced by
`make ascii-check`).

Usage:
  python3 tools/gen-dashboard.py [--check] [--template=PATH] [--out=PATH]

--check       Verify the generated file matches the template; exit 1 on
              mismatch (used by CI to fail loudly when the committed file
              drifted from resources/dashboard.html).
--template    Template source path (default: resources/dashboard.html).
--out         Output Ada spec path (default: src/adacovex-dashboard_template.ads).

Exit code 0 on success, 1 on a missing template or a --check mismatch.
"""

import argparse
import sys
from pathlib import Path
from typing import List

ROOT: Path = Path(__file__).resolve().parent.parent


def generate(out: Path, template: Path) -> None:
    """Write the Ada package spec embedding the template as a constant."""
    lines: List[str] = template.read_text(encoding="ascii").splitlines()
    # Ada string literals cannot span lines, and GNAT truncates over-long
    # source lines (the style gate is -gnatyM120), so each template line is
    # emitted as short quoted chunks joined with ` & `.  The emitted line is
    # "  & \"<chunk>\"" (6 chars of scaffolding) or, on the first line,
    # "   Template : constant String := \"<chunk>\"" (30 chars), so 88-char
    # chunks keep every emitted line well under 120.  Source lines are
    # joined with ASCII.LF (each keeps its own newline in the rendered
    # page); no trailing line feed after the last line.
    chunks: List[str] = []
    for i, line in enumerate(lines):
        chunk_max: int = 88
        for start in range(0, len(line), chunk_max):
            piece: str = line[start : start + chunk_max].replace('"', '""')
            chunks.append('"' + piece + '"')
        if i < len(lines) - 1:
            chunks.append("ASCII.LF")
    body: str = "\n  & ".join(chunks)

    header: str = (
        "--  Generated by tools/gen-dashboard.py from resources/dashboard.html.\n"
        "--  Bundled dashboard page shell for --serve: the static HTML/CSS/JS\n"
        "--  (dynamic metric cards are injected at the __CARDS__ placeholder by\n"
        "--  Adacovex.Renderers.HTML.Render_Dashboard, which also fills the\n"
        "--  __THEME__ placeholder with the initial dashboard theme).  Do not\n"
        "--  edit by hand; edit resources/dashboard.html and run make build.\n"
    )
    out.write_text(
        header
        + "package Adacovex.Dashboard_Template is\n"
        + "\n"
        + "   --  The full dashboard page shell.  __CARDS__ marks where the\n"
        + "   --  dynamic card markup is injected; __THEME__ is replaced with\n"
        + "   --  the initial theme (system / light / dark).\n"
        + "   Template : constant String :=\n"
        + body
        + ";\n"
        + "end Adacovex.Dashboard_Template;\n",
        encoding="ascii",
    )


def parse_args(argv: List[str]) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Bundle resources/dashboard.html into an Ada string constant."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed generated file matches the template",
    )
    parser.add_argument(
        "--template",
        default=str(ROOT / "resources" / "dashboard.html"),
        help="template source path (default: resources/dashboard.html)",
    )
    parser.add_argument(
        "--out",
        default=str(ROOT / "src" / "adacovex-dashboard_template.ads"),
        help="output Ada spec path (default: src/adacovex-dashboard_template.ads)",
    )
    return parser.parse_args(argv)


def main(argv: List[str]) -> int:
    """Run the generator; return the process exit code."""
    args = parse_args(argv)
    template: Path = Path(args.template).resolve()
    out: Path = Path(args.out).resolve()
    if not template.is_file():
        print(f"error: template not found: {template}", file=sys.stderr)
        return 1
    if args.check:
        before: str = out.read_text(encoding="ascii") if out.is_file() else ""
        generate(out, template)
        after: str = out.read_text(encoding="ascii")
        if before != after:
            print(
                f"error: {out.name} is stale -- run tools/gen-dashboard.py (or "
                "make build) and commit the regenerated file.",
                file=sys.stderr,
            )
            return 1
        print(f"{out.name} is up to date.")
        return 0
    generate(out, template)
    print(f"wrote {out.name} ({template.stat().st_size} bytes template)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
