#!/usr/bin/env python3
"""Generate src/adacovex-version.ads from the authoritative version source.

The single source of truth for the adacovex version is alire-dev.toml
(`version = "x.y.z"`), which is bumped by `make bump-version`.  This script
reads it and regenerates the Ada package spec that the binary is compiled
against, so `--version`, the man page, the SBOM tool version, and the result
cache path can never drift from the manifest.

Release builds bundle the version from the release tag instead: the release
workflow (and `make release` / the composite action) export ADACOVEX_VERSION
(e.g. "v1.10.0" or "1.10.0"); this script strips a leading "v" and uses it in
place of the manifest value, so the binary a release ships reports exactly
the tag it was built from.  A non-version ADACOVEX_VERSION (e.g. a branch
name in non-release CI) is ignored and the manifest value is used.

The generated file is committed so the tree builds without running this
script, and `make build` regenerates it (byte-identical when nothing
changed) so a checkout is always self-consistent.

Usage:
  python3 tools/gen-version.py [--check] [--manifest=PATH] [--out=PATH]

--check      Verify the generated file already matches the current version
             source; exit 1 on mismatch (used by CI to fail loudly when the
             committed file drifted from alire-dev.toml).
--manifest   Manifest to read the version from (default: alire-dev.toml).
--out        Output Ada spec path (default: src/adacovex-version.ads).

Exit code 0 on success, 1 on a missing/invalid version source or a --check
mismatch.
"""

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Optional, Tuple

ROOT: Path = Path(__file__).resolve().parent.parent

VERSION_RE: str = r"^\d+\.\d+\.\d+$"


def read_manifest_version(path: Path) -> Optional[str]:
    """Return the `version = "x.y.z"` value from a TOML manifest, or None."""
    if not path.exists():
        return None
    for raw in path.read_text(errors="replace").splitlines():
        line: str = raw.strip()
        if line.startswith("version"):
            m = re.match(r'version\s*=\s*"([^"]+)"', line)
            if m:
                return m.group(1)
    return None


def resolve_version(manifest: Path) -> Tuple[str, str]:
    """Return (version, source-description) honoring ADACOVEX_VERSION.

    ADACOVEX_VERSION wins when it is a parseable x.y.z (leading "v"
    stripped); otherwise the manifest value is used.  A missing version in
    both places is a hard error so the binary can never be built with an
    unknown version.
    """
    env: str = os.environ.get("ADACOVEX_VERSION", "").strip()
    if env:
        bare: str = env[1:] if env.startswith("v") else env
        if re.match(VERSION_RE, bare):
            return bare, f"ADACOVEX_VERSION ({env})"
        # Non-version env (branch name etc.): fall through to the manifest.
    ver: Optional[str] = read_manifest_version(manifest)
    if ver is None or not re.match(VERSION_RE, ver):
        raise SystemExit(
            f"error: no x.y.z version found in {manifest}"
            + (f" (ADACOVEX_VERSION='{env}' is not a version)" if env else "")
        )
    return ver, str(manifest)


def render(version: str) -> str:
    """Render the Ada package spec for a version."""
    return (
        "--  Version constant for the adacovex tool suite.\n"
        "--  GENERATED by tools/gen-version.py -- do not edit by hand.\n"
        "--  Source of truth: alire-dev.toml (`version = \"...\"`), or the\n"
        "--  ADACOVEX_VERSION environment variable for release builds, so the\n"
        "--  bundled binary always reports the exact release tag it was built\n"
        "--  from (`adacovex --version`, `adacovex man`, SBOM tool version,\n"
        "--  and the result-cache namespace all derive from this).\n"
        "\n"
        "package Adacovex_Version_Info is\n"
        "   pragma SPARK_Mode (On);\n"
        "\n"
        f'   Version : constant String := "{version}";\n'
        "\n"
        "end Adacovex_Version_Info;\n"
    )


def main(argv: Optional[list] = None) -> int:
    ap: argparse.ArgumentParser = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify the generated file is current; exit 1 on drift")
    ap.add_argument("--manifest", default=str(ROOT / "alire-dev.toml"))
    ap.add_argument("--out",
                    default=str(ROOT / "src" / "adacovex_version_info.ads"))
    args: argparse.Namespace = ap.parse_args(argv)

    version, source = resolve_version(Path(args.manifest))
    content: str = render(version)
    out: Path = Path(args.out)

    if args.check:
        if out.exists() and out.read_text() == content:
            print(f"ok: {out.name} matches {source} (v{version})")
            return 0
        print(f"error: {out.name} is out of date (source {source}: v{version})",
              file=sys.stderr)
        return 1

    out.write_text(content)
    print(f"wrote {out.relative_to(ROOT)} (v{version} from {source})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
