--  Body of Adacovex.Docs_Template: the asset lookup for the bundled offline
--  manual.  The spec (src/adacovex-docs_template.ads) is generated by
--  tools/gen-docs.py from the mdBook manual and holds the asset table; this
--  body is hand-written and stable.  It is plain runtime code (no SPARK
--  contracts): the assets are generated string data served over the socket.

package body Adacovex.Docs_Template is

   --  The asset body for a table index: the Blob slice described by the ref.
   function Content (Idx : Positive) return String is
   begin
      return
        Blob (Assets (Idx).Start .. Assets (Idx).Start + Assets (Idx).Len - 1);
   end Content;

   --  The table index whose (space-padded) Path equals Key, or 0.
   function Path_Matches (Key : String) return Natural is
      Padded : String (1 .. Max_Path) := (others => ' ');
   begin
      Padded (1 .. Key'Length) := Key;
      for I in Assets'Range loop
         if Assets (I).Path = Padded then
            return I;
         end if;
      end loop;
      return 0;
   end Path_Matches;

   --  Normalise a request subpath to a table key:
   --    "" or "/"            -> "index.html"
   --    "dir/"               -> "dir/index.html"
   --    "page"               -> "page.html"        (then "page/index.html")
   --  An exact match always wins, so "page.html" is served for "page".
   --  Returns the Assets index of the match, or 0 when absent.
   function Find (Subpath : String) return Natural is
      Cand : String (1 .. Subpath'Length + 12) := (others => ' ');
      Len  : Natural := Subpath'Length;
      Idx  : Natural;
   begin
      if Len = 0 or else (Len = 1 and then Subpath (Subpath'First) = '/') then
         Cand (1 .. 10) := "index.html";
         Len := 10;
      else
         Cand (1 .. Len) := Subpath;
         if Cand (Len) = '/' then
            Cand (Len + 1 .. Len + 10) := "index.html";
            Len := Len + 10;
         end if;
      end if;

      Idx := Path_Matches (Cand (1 .. Len));
      if Idx /= 0 then
         return Idx;
      end if;

      --  Extensionless leaf: try page.html, then page/index.html.
      if Len > 0 and then Cand (Len) /= '/' then
         Cand (Len + 1 .. Len + 5) := ".html";
         Idx := Path_Matches (Cand (1 .. Len + 5));
         if Idx /= 0 then
            return Idx;
         end if;
         Cand (Len + 1 .. Len + 11) := "/index.html";
         return Path_Matches (Cand (1 .. Len + 11));
      end if;

      return 0;
   end Find;

end Adacovex.Docs_Template;
