--  Generated by tools/gen-dashboard.py from resources/dashboard.html.
--  Bundled dashboard page shell for --serve: the static HTML/CSS/JS
--  (dynamic metric cards are injected at the __CARDS__ placeholder by
--  Adacovex.Renderers.HTML.Render_Dashboard, which also fills the
--  __THEME__ placeholder with the initial dashboard theme).  Do not
--  edit by hand; edit resources/dashboard.html and run make build.
package Adacovex.Dashboard_Template is

   --  The full dashboard page shell.  __CARDS__ marks where the
   --  dynamic card markup is injected; __THEME__ is replaced with
   --  the initial theme (system / light / dark).
   Template : constant String :=
"<!DOCTYPE html><html lang=""en"" data-initial-theme=""__THEME__""><head><meta charset=""UTF-8""><title>adacovex Dashboard</tit"
  & "le><style>:root{--bg:#f5f5f5;--fg:#333;--card:#fff;--border:#ddd;--th:#f0f0f0;--pass:#4c1;--fail:#e05d44;--muted:#888}@m"
  & "edia (prefers-color-scheme:dark){:root{--bg:#1e1e1e;--fg:#e0e0e0;--card:#2d2d2d;--border:#444;--th:#3a3a3a;--pass:#8bc34"
  & "a;--fail:#ff6b5e;--muted:#999}}:root[data-theme=""dark""]{--bg:#1e1e1e;--fg:#e0e0e0;--card:#2d2d2d;--border:#444;--th:#3a3"
  & "a3a;--pass:#8bc34a;--fail:#ff6b5e;--muted:#999}:root[data-theme=""light""]{--bg:#f5f5f5;--fg:#333;--card:#fff;--border:#dd"
  & "d;--th:#f0f0f0;--pass:#4c1;--fail:#e05d44;--muted:#888}body{font-family:DejaVu Sans,sans-serif;margin:40px;background:va"
  & "r(--bg);color:var(--fg)}h1{color:var(--fg)}.dash-header{display:flex;justify-content:space-between;align-items:center;fl"
  & "ex-wrap:wrap;gap:12px}.card{background:var(--card);border-radius:8px;padding:20px;margin:16px 0;box-shadow:0 2px 4px rgb"
  & "a(0,0,0,.1)}table{width:100%;border-collapse:collapse}th,td{padding:8px 12px;text-align:left;border-bottom:1px solid var"
  & "(--border)}th{background:var(--th)}.badge-container{display:flex;gap:16px;flex-wrap:wrap}.badge-container svg{height:20p"
  & "x}.pass{color:var(--pass);font-weight:bold}.fail{color:var(--fail);font-weight:bold}.spark{font-weight:bold}.theme-toggl"
  & "e{background:var(--card);color:var(--fg);border:1px solid var(--border);border-radius:6px;padding:8px 14px;cursor:pointe"
  & "r;font-size:0.9em;font-family:inherit}.theme-toggle:hover{border-color:var(--pass)}.theme-label{color:var(--muted);font-"
  & "size:0.9em;margin-right:6px}.footer{color:var(--muted);font-size:0.8em;margin-top:24px}</style></head><body>"
  & ASCII.LF
  & "<div class=""dash-header""><h1>adacovex Coverage &amp; Verification Dashboard</h1><label class=""theme-label"" for=""theme-se"
  & "lect"">Theme</label><select id=""theme-select"" class=""theme-toggle"" onchange=""themeChanged()"" title=""Pin the theme when em"
  & "bedding: append ?theme=light|dark|system""><option value=""system"">system</option><option value=""light"">light</option><opt"
  & "ion value=""dark"">dark</option></select><button id=""save-theme"" class=""theme-toggle"" onclick=""saveTheme()"">Save settings<"
  & "/button></div>"
  & ASCII.LF
  & "<!--__CARDS__-->"
  & ASCII.LF
  & "<p class=""footer"">Generated by adacovex &middot; Embed: append <code>?theme=light|dark|system</code> to the URL to pin t"
  & "he theme.</p>"
  & ASCII.LF
  & "<script>"
  & ASCII.LF
  & "(function(){var K='adacovex-theme',R=document.documentElement,S=document.getElementById('theme-select'),B=document.getEl"
  & "ementById('save-theme');var C=R.getAttribute('data-initial-theme')||'system';function apply(t){if(t==='dark')R.setAttrib"
  & "ute('data-theme','dark');else if(t==='light')R.setAttribute('data-theme','light');else R.removeAttribute('data-theme');}"
  & "function pick(){return S?S.value:'system';}var use='system';var q=null;try{q=new URLSearchParams(location.search).get('t"
  & "heme');}catch(e){}if(q==='light'||q==='dark'||q==='system'){use=q;}else if(C==='light'||C==='dark'){use=C;}else{var s=nu"
  & "ll;try{s=localStorage.getItem(K);}catch(e){}if(s==='light'||s==='dark'||s==='system'){use=s;}}if(S)S.value=use;apply(use"
  & ");window.themeChanged=function(){apply(pick());};window.saveTheme=function(){var t=pick();try{localStorage.setItem(K,t);"
  & "}catch(e){}if(B){B.textContent='Saved';setTimeout(function(){B.textContent='Save settings';},1200);}};})();"
  & ASCII.LF
  & "</script>"
  & ASCII.LF
  & "</body></html>";
end Adacovex.Dashboard_Template;
