--  Body of Adacovex.Docs_Template: the asset lookup for the bundled offline
--  manual.  The spec (src/adacovex-docs_template.ads) is generated by
--  tools/gen-docs.py from the Sphinx manual (docs/conf.py + MyST) and holds
--  the asset table; this body is hand-written and stable.  The asset bodies
--  are gzip bytes base85-encoded (see the generator), so this body also
--  carries the small base85 decoder that turns a body back into the gzip
--  stream the server sends with Content-Encoding: gzip.  base85 costs 1.25
--  characters per byte where base64 costs 1.333, and the Ada source stays
--  pure ASCII either way.  It is plain runtime code (no SPARK contracts):
--  the assets are generated string data served over the socket.

package body Adacovex.Docs_Template is

   --  Decode one base85 chunk into its raw byte String.  Four bytes become
   --  five characters on the quote-free Z85 alphabet (digits, lower case,
   --  upper case, then the punctuation run), most significant first.  A
   --  final group of 1..3 bytes carries only n+1 characters: the decoder
   --  pads it with the last alphabet value, which restores the zero padding
   --  the encoder added, and drops the padding bytes.  The bounds are
   --  derived from S'Length, so a chunk never allocates beyond its own size.
   function Base85_Decode (S : String) return String is
      subtype Acc_Index is Positive range 1 .. (S'Length / 5 + 1) * 4;

      Punctuation : constant String := ".-:+=^!/*?&<>()[]{}@%$#";

      function Val (C : Character) return Natural is
      begin
         if C in '0' .. '9' then
            return Character'Pos (C) - Character'Pos ('0');
         elsif C in 'a' .. 'z' then
            return 10 + Character'Pos (C) - Character'Pos ('a');
         elsif C in 'A' .. 'Z' then
            return 36 + Character'Pos (C) - Character'Pos ('A');
         end if;
         for I in Punctuation'Range loop
            if Punctuation (I) = C then
               return 62 + (I - Punctuation'First);
            end if;
         end loop;
         return 0;  --  any unexpected character decodes to 0
      end Val;

      Out_Acc : String (Acc_Index) := (others => ASCII.NUL);
      N       : Natural := 0;
   begin
      declare
         I : Positive := S'First;
      begin
         while I <= S'Last loop
            declare
               Last : constant Natural := Natural'Min (I + 4, S'Last);
               Gone : constant Natural := Last - I + 1;
               --  Five base-85 digits reach 85**5 - 1, about 4.4e9, which
               --  overflows a 32-bit Natural.  Long_Long_Integer holds the
               --  group value on every platform the tool builds for.
               V    : Long_Long_Integer := 0;
            begin
               for K in I .. Last loop
                  V := V * 85 + Long_Long_Integer (Val (S (K)));
               end loop;
               --  A short final group pads with the highest digit, which
               --  restores the encoder's zero bytes, and yields Gone - 1
               --  payload bytes.
               for K in 1 .. 5 - Gone loop
                  V := V * 85 + 84;
               end loop;
               --  Big-endian bytes, masked so every value stays in range.
               Out_Acc (Acc_Index (N + 1)) :=
                 Character'Val (Integer ((V / 16#1000000#) mod 256));
               if Gone > 2 then
                  Out_Acc (Acc_Index (N + 2)) :=
                    Character'Val (Integer ((V / 16#10000#) mod 256));
               end if;
               if Gone > 3 then
                  Out_Acc (Acc_Index (N + 3)) :=
                    Character'Val (Integer ((V / 256) mod 256));
               end if;
               if Gone > 4 then
                  Out_Acc (Acc_Index (N + 4)) :=
                    Character'Val (Integer (V mod 256));
               end if;
               N := N + (Gone - 1);
            end;
            exit when I + 4 >= S'Last;
            I := I + 5;
         end loop;
      end;
      return Out_Acc (Out_Acc'First .. Out_Acc'First + N - 1);
   end Base85_Decode;

   --  The decoded bytes of one body constant: base85-decoded (the gzip
   --  stream) when Is_Gzip, verbatim otherwise.  Serves one compressed chunk,
   --  so a worker never materialises a whole multi-megabyte asset at once.
   function Body_Bytes (B : Body_Index; Is_Gzip : Boolean) return String is
      Raw : constant String := Asset_Bodies (B).all;
   begin
      if Is_Gzip then
         return Base85_Decode (Raw);
      end if;
      return Raw;
   end Body_Bytes;

   --  The decoded first body of a table asset (its only body for every asset
   --  unless a gzip chunk split it).
   function Content (Idx : Asset_Index) return String is
   begin
      return Body_Bytes (Assets (Idx).Idx, Assets (Idx).Gzip);
   end Content;

   --  The table index whose (space-padded) Path equals Key, or 0.
   function Path_Matches (Key : String) return Natural is
      Padded : String (1 .. Max_Path) := (others => ' ');
   begin
      Padded (1 .. Key'Length) := Key;
      for I in Assets'Range loop
         if Assets (I).Path = Padded then
            return I;
         end if;
      end loop;
      return 0;
   end Path_Matches;

   --  Normalise a request subpath to a table key:
   --    "" or "/"            -> "index.html"
   --    "dir/"               -> "dir/index.html"
   --    "page"               -> "page.html"        (then "page/index.html")
   --  An exact match always wins, so "page.html" is served for "page".
   --  Returns the Assets index of the match, or 0 when absent.
   function Find (Subpath : String) return Natural is
      Cand : String (1 .. Subpath'Length + 12) := (others => ' ');
      Len  : Natural := Subpath'Length;
      Idx  : Natural;
   begin
      if Len = 0 or else (Len = 1 and then Subpath (Subpath'First) = '/') then
         Cand (1 .. 10) := "index.html";
         Len := 10;
      else
         Cand (1 .. Len) := Subpath;
         if Cand (Len) = '/' then
            Cand (Len + 1 .. Len + 10) := "index.html";
            Len := Len + 10;
         end if;
      end if;

      Idx := Path_Matches (Cand (1 .. Len));
      if Idx /= 0 then
         return Idx;
      end if;

      --  Extensionless leaf: try page.html, then page/index.html.
      if Len > 0 and then Cand (Len) /= '/' then
         Cand (Len + 1 .. Len + 5) := ".html";
         Idx := Path_Matches (Cand (1 .. Len + 5));
         if Idx /= 0 then
            return Idx;
         end if;
         Cand (Len + 1 .. Len + 11) := "/index.html";
         return Path_Matches (Cand (1 .. Len + 11));
      end if;

      return 0;
   end Find;

end Adacovex.Docs_Template;
