--  Body of Adacovex.Docs_Template: the asset lookup for the bundled offline
--  manual.  The spec (src/adacovex-docs_template.ads) is generated by
--  tools/gen-docs.py from the Sphinx manual (docs/conf.py + MyST) and holds
--  the asset table; this body is hand-written and stable.  The asset bodies
--  are gzip bytes base64-encoded (see the generator), so this body also
--  carries the small base64 decoder that turns a body back into the gzip
--  stream the server sends with Content-Encoding: gzip.  It is plain
--  runtime code (no SPARK contracts): the assets are generated string data
--  served over the socket.

package body Adacovex.Docs_Template is

   --  Decode one standard base64 chunk (with optional trailing '=' padding)
   --  into its raw byte String.  The durations are bounded by the chunk
   --  length, so this never allocates beyond a single compressed chunk.
   function Base64_Decode (S : String) return String is
      subtype Acc_Index is Positive range 1 .. (S'Length / 4 + 1) * 3;

      function Val (C : Character) return Natural is
      begin
         if C in 'A' .. 'Z' then
            return Character'Pos (C) - Character'Pos ('A');
         elsif C in 'a' .. 'z' then
            return 26 + Character'Pos (C) - Character'Pos ('a');
         elsif C in '0' .. '9' then
            return 52 + Character'Pos (C) - Character'Pos ('0');
         elsif C = '+' then
            return 62;
         elsif C = '/' then
            return 63;
         end if;
         return 0;  --  '=' or any unexpected character decodes to 0
      end Val;

      Out_Acc : String (Acc_Index) := (others => ASCII.NUL);
      N       : Natural := 0;
   begin
      declare
         I : Positive := S'First;
      begin
         while I <= S'Last loop
            declare
               C0 : constant Character := S (I);
               C1 : Character := 'A';
               C2 : Character := 'A';
               C3 : Character := 'A';
               V  : Natural;
            begin
               if I < S'Last then
                  C1 := S (I + 1);
               end if;
               if I + 1 < S'Last then
                  C2 := S (I + 2);
               end if;
               if I + 2 < S'Last then
                  C3 := S (I + 3);
               end if;
               V :=
                 Val (C0)
                 * 262144
                 + Val (C1) * 4096
                 + Val (C2) * 64
                 + Val (C3);
               --  6-bit sextets back to bytes (big-endian)
               Out_Acc (Acc_Index (N + 1)) := Character'Val (V / 65536);
               Out_Acc (Acc_Index (N + 2)) :=
                 Character'Val ((V / 256) mod 256);
               Out_Acc (Acc_Index (N + 3)) := Character'Val (V mod 256);
               N := N + 3;
            end;
            I := I + 4;
         end loop;
      end;
      --  The final padding '='s decode to zero bytes that we strip: each '='
      --  removes one trailing byte.
      declare
         Pad : Natural := 0;
      begin
         for I in reverse S'Range loop
            exit when S (I) /= '=';
            Pad := Pad + 1;
         end loop;
         N := N - Pad;
      end;
      return Out_Acc (Out_Acc'First .. Out_Acc'First + N - 1);
   end Base64_Decode;

   --  The decoded bytes of one body constant: base64-decoded (the gzip
   --  stream) when Is_Gzip, verbatim otherwise.  Serves one compressed chunk,
   --  so a worker never materialises a whole multi-megabyte asset at once.
   function Body_Bytes (B : Body_Index; Is_Gzip : Boolean) return String is
      Raw : constant String := Asset_Bodies (B).all;
   begin
      if Is_Gzip then
         return Base64_Decode (Raw);
      end if;
      return Raw;
   end Body_Bytes;

   --  The decoded first body of a table asset (its only body for every asset
   --  unless a gzip chunk split it).
   function Content (Idx : Asset_Index) return String is
   begin
      return Body_Bytes (Assets (Idx).Idx, Assets (Idx).Gzip);
   end Content;

   --  The table index whose (space-padded) Path equals Key, or 0.
   function Path_Matches (Key : String) return Natural is
      Padded : String (1 .. Max_Path) := (others => ' ');
   begin
      Padded (1 .. Key'Length) := Key;
      for I in Assets'Range loop
         if Assets (I).Path = Padded then
            return I;
         end if;
      end loop;
      return 0;
   end Path_Matches;

   --  Normalise a request subpath to a table key:
   --    "" or "/"            -> "index.html"
   --    "dir/"               -> "dir/index.html"
   --    "page"               -> "page.html"        (then "page/index.html")
   --  An exact match always wins, so "page.html" is served for "page".
   --  Returns the Assets index of the match, or 0 when absent.
   function Find (Subpath : String) return Natural is
      Cand : String (1 .. Subpath'Length + 12) := (others => ' ');
      Len  : Natural := Subpath'Length;
      Idx  : Natural;
   begin
      if Len = 0 or else (Len = 1 and then Subpath (Subpath'First) = '/') then
         Cand (1 .. 10) := "index.html";
         Len := 10;
      else
         Cand (1 .. Len) := Subpath;
         if Cand (Len) = '/' then
            Cand (Len + 1 .. Len + 10) := "index.html";
            Len := Len + 10;
         end if;
      end if;

      Idx := Path_Matches (Cand (1 .. Len));
      if Idx /= 0 then
         return Idx;
      end if;

      --  Extensionless leaf: try page.html, then page/index.html.
      if Len > 0 and then Cand (Len) /= '/' then
         Cand (Len + 1 .. Len + 5) := ".html";
         Idx := Path_Matches (Cand (1 .. Len + 5));
         if Idx /= 0 then
            return Idx;
         end if;
         Cand (Len + 1 .. Len + 11) := "/index.html";
         return Path_Matches (Cand (1 .. Len + 11));
      end if;

      return 0;
   end Find;

end Adacovex.Docs_Template;
