--  Version constant for the adacovex tool suite.
--  GENERATED by tools/gen-version.py -- do not edit by hand.
--  Source of truth: alire-dev.toml (`version = "..."`), or the
--  ADACOVEX_VERSION environment variable for release builds, so the
--  bundled binary always reports the exact release tag it was built
--  from (`adacovex --version`, `adacovex man`, SBOM tool version,
--  and the result-cache namespace all derive from this).

package Adacovex_Version_Info is
   pragma SPARK_Mode (On);

   Version : constant String := "1.11.0";

end Adacovex_Version_Info;
