--  Version constant for the adacovex tool suite.
--  GENERATED by tools/gen-version.py -- do not edit by hand.
--  The version source depends on the installation method: the
--  ADACOVEX_VERSION env var for release builds, alire-dev.toml for
--  source checkouts, or alire.toml (the toml associated with the
--  covex binary for dependency management) when the crate is built
--  as a dependency. `adacovex --version`, `adacovex man`, the SBOM
--  tool version, and the result-cache namespace derive from it.

package Adacovex_Version_Info is
   pragma SPARK_Mode (On);

   Version : constant String := "1.42.0";

end Adacovex_Version_Info;
